steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.weekly-estimates', '-t', 'us-central1-docker.pkg.dev/yfinance-cli/tek2day/weekly-estimates:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/yfinance-cli/tek2day/weekly-estimates:latest'
